defaults:
  - default

model:
  _target_: models.cnn_lstm.CNNLSTM
  _partial_: true
  hidden_size: 64
  num_layers: 2
  dropout: 0.1
  # CNN backbone parameters
  cnn_n_blocks: [1, 1]
  cnn_planes_per_branch: [32, 64]
  cnn_target_planes: [32, 64]
