defaults:
  - default

model:
  _target_: models.cnn_transformer.CNNTransformer
  _partial_: true
  d_model: 64
  nhead: 4
  num_layers: 6
  dim_feedforward: 128
  dropout: 0.1
  base_dim: 32
  n_blocks: [2, 2]
  planes_per_branch: [32, 64]
  target_planes: [32, 64]
