defaults:
  - default

model:
  _target_: models.timemixer.TimeMixer
  _partial_: true
  d_model: 32
  d_ff: 64
  e_layers: 4
  seq_len: 64
  down_sampling_layers: 4
  down_sampling_window: 2
  down_sampling_method: avg
  decomp_method: dft_decomp
  moving_avg: 25
  top_k: 5
  dropout: false
