defaults:
  - default

model:
  _target_: models.simple_transformer.SimpleTransformer
  _partial_: true
  d_model: 64
  nhead: 4
  num_layers: 4
  dim_feedforward: 256
  dropout: 0.2
  use_coin_embedding: true
