defaults:
  - default

model:
  _target_: models.simple_transformer.SimpleTransformer
  _partial_: true
  d_model: 64
  nhead: 8
  num_layers: 4
  dim_feedforward: 256
  dropout: 0.1

trade_loss:
  _target_: loss.binary_focal_loss.BinaryFocalLoss
  alpha: 0.5
  gamma: 2.0
  reduction: "mean"

learning_rate: 1e-3
