# @package _global_

defaults:
  - _self_
  - data: crypto
  - model: null
  - callbacks: default
  - logger: csv # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  # config for hyperparameter optimization
  - hparams_search: null

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# task name, determines output directory path
task_name: "train"

tags: ["dev"]

train: True

test: True

ckpt_path: null

seed: 24
